### ISSUE TITLE
slurping does nothing

### ISSUE THREAD

**Issue by khurtwilliams** [kraftbj/beer-slurper#10]
I installed the plugin. Installed WP CLI. 

Set

`function bs_test_insert( $user = 'khurtwilliams' )`

Ran

`wp eval 'bs_start_import( "khurtwilliams" );`

and ... happens.

Is there more to the installation and usage than what is in the readme.txt?

**Comment by kraftbj** [comment]
Things are working for you now. I'll definitely need to make this more robust and easier to get started if I ever consider this for release :)

**Comment by khurtwilliams** [comment]
Thank you for this. I would prefer if the information pulled was included
in the post.

More like this:
https://islandinthenet.com/wildcard-brewing-co-s-crowd-pleaser/

But this is a good start:
https://islandinthenet.com/beers/wildcard-brewing-co-crowd-pleaser/
